### PR TITLE
update golang version

### PR DESCRIPTION
**Pull request by mavimo**
## Changes
 - Update golang version to 1.16.2 for CI
 - Update golang version to 1.16.2 for docker image

@malcolmholmes I can't sign the `.drone.yaml` can you run `make drone` from this branch? Thanks!

### CODE REVIEW

**Review by malcolmholmes — COMMENTED** [review]
I'm working on a PR that requires 1.16 right now. Any reason to require 1.16.2 rather than just 1.16?

Also, you need to edit `.drone/drone.jsonnet` then run the `drone` target rather than manually updating `drone.yml`.

I can see if I can sign it. Not sure I've done that before.

**Comment by mavimo** [comment]
@malcolmholmes I prefer to require the specific patch version to make build reproducible. If we use `1.16` different build with the same codebase can produce a different result.

> Also, you need to edit .drone/drone.jsonnet then run the drone target rather than manually updating drone.yml.

is what I do, but since I don't have an account in the drone.grafana.net I can't sign the resulting code.

PS: I dunno how your drone server is configured but drone is able to process jsonnet file so there is no need to dump the yaml file :)

**Comment by malcolmholmes** [comment]
There's various complications regarding Jsonnet in Drone - I don't recall them (e.g. I think to do with importing libraries). Our conclusion is that it is simpler to run the Jsonnet ourselves and commit a YAML.

Can you update the Jsonnet file in this PR?

**Comment by mavimo** [comment]
@malcolmholmes I'm not sure to understand what I need to update, the golang version in the jsonnet file was already updated, see https://github.com/grafana/grizzly/pull/93/files#diff-60045f9474705196e786df20a7bb40d29e013e47a3b6927153a10b9acac82266L1 but when I run `make drone` to dump the YAML file it fail on the signing process (that fail because I'm not in the grafana organization).

I'm missing something?

**Comment by malcolmholmes** [comment]
Okay, I missed that, thanks.

I can sign the file, but I can't add it to this branch. I think you are able to add me to this PR, can you do that? https://stackoverflow.com/questions/44030176/how-to-modify-someone-elses-github-pull-request/45114109

**Comment by mavimo** [comment]
@malcolmholmes "Allow maintainers to edit" was already active, can you double check if it work?

image

**Review by malcolmholmes — APPROVED** [review]
Great, thanks for this!

**Pull request merged**
