### PR TITLE
Fix dashboard preview to ignore folder resources

### PR DESCRIPTION
**Pull request by DeathBorn**
Preview should not be created for dashboard folder resource.

### CODE REVIEW

**Review by malcolmholmes — APPROVED** [review]
Thanks, makes sense!

**Comment by DeathBorn** [comment]
👌 also, I think I have an idea regarding grafanaFolders problem with `{}`. I think if it would work just like grafanaDashboards, then there will be no problem and on a plus side, additional folder management functionality.

**Comment by malcolmholmes** [comment]
The folders functionality is in place for legacy reasons, the `grafanaDashboardFolder` element is in use.

However, a better design that actually specifies a folder with title and uid, would  be better, especially if it were backwards compatible.

**Comment by DeathBorn** [comment]
Ah.. `grafanaDashboardFolders` would make sense then 🤦

**Pull request merged**
