### PR TITLE
Fix `grr get` of an AlertRuleGroup with UID containing dots

### LINKED ISSUE #516: [Bug]: AlertRuleGroup get command fails with UID-s containing dot .
### Grizzly Version

 v0.6.0

### Expected Behavior

Get the alert rule group spec

### Actual Behavior

Error : FATAL couldn't find a handler for `AlertRuleGroup.<some-uid>`: handler not found

### Steps to Reproduce

- retrieve alert rule groupes using `grr list -r -t AlertRuleGroup`
- UIDs are formatted like this : `<some-uid>.<some-text>`
- try to get one of these alert rule groups : `grr get AlertRuleGroup.<some-uid>.<some-text>`

### PR DESCRIPTION
**Pull request by K-Phoen**
Fixes #516 

Fixes the logic used by `grr get` to split the Handler name from the rest of the UID.

### CODE REVIEW

**Review by Pokom — APPROVED** [review]
Source code changes looks reasonable enough for me 👍🏻

**Comment by K-Phoen** [comment]
I want to do some more tests tomorrow, from [this bit](https://github.com/grafana/grizzly/pull/517/files#diff-1c2bc400869dd54ad3f708aebc293bb446249797cd4d64de029df22eaf5376fcL28-L39) of code it looks like handler names can be composed of two parts (which surprises me). I feel like a bit more checks are required, in case I break something I'm just not aware of (that also wouldn't be covered by tests :sweat_smile:)

**Comment by malcolmholmes** [comment]
"this bit" above is needed for Synthetic Monitoring, IIRC, as a check didn't have a unique identifier - so we needed to use its name and type to make a unique identifier.

**Comment by K-Phoen** [comment]
Thanks for the tip :)

I tested with SM checks and it seems to work fine.

**Pull request merged**
